name: Deploy Laravel App

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the artifact from GitHub
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: laravel-release

      # 2. Copy artifact to server (/tmp)
      - name: Upload to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "release.tar.gz"
          target: "/tmp"

      # 3. SSH into server and deploy
      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ${{ secrets.DEPLOY_SCRIPT }}
